sprint_9#1
AleksandrRudinskiy/java-filmorate pull request #1
Opened 2023-12-26 19:42 UTC by AleksandrRudinskiy

2023-12-26 20:21 UTC, AleksandrRudinskiy commented
qwe

2023-12-27 17:38 UTC, dgumich requested changes

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService = new FilmService();
Нет, нет и еще раз нет=)
Забудь про создание объектов через new.
Так делают только при создании бина в конфигурационном классе. Все остальное идет через внедрение зависимостей. Спринг сам создает объект (называется бином) и внедряет где его нужно.
Советую изучить эту часть еще раз.

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
В задании была подсказка как можно создать логгер с помощью ломбока

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Current number of films: {}", filmService.getFilms().size());
Два раза получать список это плохо. Надо его получить, сохранить в локальной переменной, затем уже в логгировани вывести его размер и вернуть в конце метода.

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@RequestBody Film film) {
Правильные названия методов никто не отменял=)
POST используется для создания фильма. Так и назови метод : createFilm

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film saveFilm(@RequestBody Film film, HttpServletResponse response) {
PUT используется для обновления, а не сохранения, так что правильное название будет updateFilm

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.info("Film updated" + film.getName());
Логировать надо после совершения действия, а не до.
Вдруг во время обновления словим исключение, а в логах уже будет написано, что фильм обновлен.

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserService userService = new UserService();
Аналогично, ничего не создаем через new, если это не конфигурационный класс.

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.debug("Текущее количество пользователей: {}", userService.getUsers().size());
Аналогично, не надо два раза ходить в сервис за списком пользователей. Надо сохранить его в локальную переменную.

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<User> findAll() {
Название метода не полное. findAllUsers

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User create(@RequestBody User user) {
Плохое название метода, надо исправить.

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User saveUser(@RequestBody User user, HttpServletResponse response) {
Название метода так же не подходит, должно быть обновитьПользователя, а не сохранитьПользователя

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmService.java
> +        for (Film item : films.values()) {
А это вообще что такое?0_о Мы уже работали с мапой и знаем, что есть есть метод, который проверяет по ключу есть ли такое ключ/значение в мапе или нет. Надо исправить

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmService.java
> +        if (films.containsKey(film.getId())) {
Можешь объяснить как это уживается использование метода containsKey и логика метода isAlreadyExists ?=)
Почему здесь используешь то что нужно, а в isAlreadyExists создаешь велосипед?

2023-12-27 17:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/UserService.java
> +        for (User item : users.values()) {
Аналогично, зачем нам тут велосипед?=)

2023-12-28 16:08 UTC, dgumich approved these changes

2023-12-28 16:08 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@RequestBody Film film, HttpServletResponse response) {
Вы пока только начали проходить спринг и сделали по сути мааааааленьки шаг, так что это ок сетапить статус в респонсе.
Но спринг предлагает куда более удобный путь работы с ответами - ResponsEntity
Можешь почитать здесь
https://www.baeldung.com/spring-response-entity
С ним нам отпадает необходимость в  HttpServletResponse response. Но это все точности, которые со спрингом будешь проходить все время работы, потому что он оооочень большой и очень гибкий=)

2023-12-28 16:08 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void filmValidate(Film film) {
Ну уже стыдно делать такие ошибки в 9 работе=) Название метода строится из глагол+существительное
То есть должно быть наоборот validateFilm=)

2023-12-28 16:08 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Советую изучить валидацию через аннотации, потому что
1) Это на самом деле проще чем делать свои методы валидации (работает буквально с помощью нескольких аннотаций)
2) В последующей работе должна быть валидация, так что с ней все равно придется разобраться=)

2023-12-28 16:08 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Request received!");
Не очень информативное логгирование. Что за реквест? Что он хочет? Должно быть более подробное, что-нибудь в стиле "Принят GET запрос на получение списка всех фильмов"

2024-01-06 15:51 UTC, merged