Add friends likes
AleksandrRudinskiy/java-filmorate pull request #2
Opened 2024-01-09 19:28 UTC by AleksandrRudinskiy

2024-01-10 14:31 UTC, AleksandrRudinskiy commented
Добавил обработку кодов ответа через ResponseEntity

2024-01-10 17:45 UTC, dgumich requested changes

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        List<Film> films = filmService.getFilmStorage().getFilms();
Нененене, сторедж остается в сервисе, в контроллере мы его не вызываем. То есть так же должен остаться метод filmService.getFilms(), а внутри этого метода уже будем вызывать у сторедж getFilms().
Контроллеры работают с сервисом, а уже сервис работает с репозиториями/сторедж/дао.

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage = new InMemoryFilmStorage();
Нет это работает не так. Теперь уже прошли внедрение зависимостей так что забывай про new.
Конструктор должен принимать  filmStorage и сетапить его полю на строке 18

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmStorage filmStorage;
Не забываем, что поля должны быть приватными

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .limit(10).collect(Collectors.toList());
Это вообще странно. Часть логики оставил в контроллере, часть в сервисе. Причем в контроллере ограничиваешь количество возвращаемых фильмов по заданному параметру (или дефолт=10). Но тебя не смущает, что в сервисе ты уже ограничил размер = 10?=)То есть мы уже не сможем вернуть больше 10, даже если пользователь попросит 100.

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getBestFilms().stream()
Слишком много логики в контроллере. Логика должна быть заключена в сервисном слое. 
Как должно быть: return filmService.getBestFilms(count), а уже он будет возвращать готовый список.

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Optional<Film> optionalFilm = filmService.getFilmStorage().getFilms().stream()
Аналогично, слишком много логики в контроллере. Должны просто вызывать filmService.getFilmById(filmId)

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Optional<Film>> getFilmById(@PathVariable int filmId) {
Нет, Optional не возвращают. Или фильм есть и тогда вернем просто Film или его нет, тогда можем кинуть исключение и в ExceptionHandler обработать исключение.

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                .filter(item -> item.getId() == filmId)
Такого даже в сервисном классе не должно быть. Что это за логика? Получить весь список и проитерироваться по всему, сравнивая айдишники. Долго, не правильно и велосипед=) Просто добавь в сторадж метод getFilmById и все, доставай из мапы по айди.

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmService.getFilmStorage().add(film);
Так же, никакой работы со стореджем в контроллере. У него даже геттера не должно быть.

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmService.getFilmStorage().isAlreadyExists(film)) {
Аналогично, логика должна быть в сервисном методе.

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        List<User> users = userService.getUserStorage().getUsers();
Аналогично, никаких слоев работы с "бд" (стореджей) в контроллере

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .filter(item -> item.getId() == id)
Так же необходимо вынести логику из контроллера и добавить метод в сторедж, что бы можно было достать по id

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public ResponseEntity<Optional<User>> getUserById(@PathVariable int userId) {
Аналогично, никаких Optional в  ResponseEntity

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        updateLikes.add(userId);
Опять велосипед=) Зачем мы создаем какой-то промежуточный сет? Как сейчас: достали сет с лайками из фильма, создали на его базе новый сет (который будет иметь все те же данные), добавили в новом сете лайке и теперь у фильма сделаем сетап лайков новым сетом. Уууууух=) Все проще: взяли у фильма сет с лайками, добавили туда лайк и дело сделано.

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> updateLikes = new HashSet<>(film.getLikes());
Аналогично, никакого промежуточно сета не нужно

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage = new InMemoryUserStorage();
Так же надо исправить. Никаких new, userStorage должен передаваться в качестве параметра в конструктор.

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Long> updateFriends = new HashSet<>(user.getFriends());
Аналогично, промежуточные сеты не нужны

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +
Надо добавить метод, который возвращает фильм по id

2024-01-10 17:45 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private void validateFilm(Film film) {
Валидация фильма должна быть на уровне сервиса. В сторедже мы только сохраняем/обновляем/удаляем данные. То есть работаем с хранилищем.

2024-01-11 03:12 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage = new InMemoryFilmStorage();
Исправил

2024-01-11 03:13 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmStorage filmStorage;
Исправил

2024-01-11 03:39 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .limit(10).collect(Collectors.toList());
Согласен) исправил)

2024-01-11 03:44 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getBestFilms().stream()
Логику перенес)

2024-01-11 03:46 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> updateLikes = new HashSet<>(film.getLikes());
Промежуточный сет убрал

2024-01-11 04:03 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage = new InMemoryUserStorage();
Исправил

2024-01-11 04:03 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Long> updateFriends = new HashSet<>(user.getFriends());
Исправил

2024-01-11 08:50 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +
Метод добавил

2024-01-11 09:49 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private void validateFilm(Film film) {
Перенес в сервисы в классах User и Film

2024-01-11 09:50 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        List<Film> films = filmService.getFilmStorage().getFilms();
Сделано)

2024-01-12 01:13 UTC, dgumich requested changes

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.info("Accepted GET request to get a list of all movies");
Данное логгирование надо сделать перед тем как мы запросим все фильмы. В чем смысл: в реальности все это будет иметь кучерявую логику в сервисе плюс работа с базой данных.  В таких местах часто получаем ошибки/исключения. Плюс там так же будет логгирование. И вот в логах будет: пошел в бд, достал фильмы, поступил гет запрос на получение всех фильмов. Порядок какой-то не такой=) Кроме того если произойдет ошибка и допустим, не будет никаких логов в ней, то мы даже не узнаем, что получили гет запрос.

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film createFilm(@RequestBody Film film) {
Должно быть единообразие: сверху возвращаешь ResponseEntity<Film>, а здесь уже просто Film. Надо привести к одному стилю=)

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                    .body(filmService.update(film));
Сначала сделай апдейт, а уже потом посылай статус, что все ок. А то может быть какая-нибудь ошибка будет=)

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Optional<Film> film = filmService.getFilms().stream()
Почему здесь не используешь Film film = filmService.getFilmById(filmId) ?

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                    .body(filmService.addLike(film.get(), userId));
На 74 строке уже сделали filmService.addLike(film.get(), userId).
Надо выполнить операцию, а уже потом ее класть в боди респонс энтит.

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(film.get());
А зачем делаешь body(film.get())? Это же кейс, когда фильма нет, то есть он равен null

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NotFoundException("filmId не найден");
Будет не очень понятно: 5 не найден. Что за 5? Где его искали? Ошибки надо логировать/сообщать подробно и ясно. Потом по ним будешь пытаться понять, что не так=)

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>          List<User> users = userService.getUsers();
Аналогично, логгирование о том, что пришел гет запрос надо вынести в начало метода

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        Set<Long> friendsId = new HashSet<>(user.getFriends());
Зачем нужен new HashSet<>? user.getFriends() и так вернет сет, так что можно просто записать Set<Long> friendsId = ser.getFriends()

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<User> getFriendsUser(@PathVariable long id) {
Правильней будет getUserFriends=)

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        User user1 = userService.getUserById(id);
fistUser, а не user1

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        User user2 = userService.getUserById(otherId);
secondUser=)

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        User friendUser = userService.getUserById(friendId);
userFriend=)

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Исключения должны быть в одном пакете. Обычно создается папка exception и там лежат все кастомные исключения

2024-01-12 01:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ExceptionHandler
Хороший тон в аннотации указывать класс исключения, который надо перехватить. Улучшает читаемость кода:
@ExceptionHandler(ValidationException.class)

2024-01-12 06:32 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.info("Accepted GET request to get a list of all movies");
Данную запись в лог перенес до запроса листа

2024-01-12 06:35 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public Film createFilm(@RequestBody Film film) {
Сделал возвращаемое значение ResponseEntity

2024-01-12 06:40 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                    .body(filmService.update(film));
Сделал предварительный update

2024-01-13 01:08 UTC, dgumich requested changes

2024-01-13 01:08 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NotFoundException("filmId не найден");
Опять непонятно, какой filmId не найден? Надо писать подробно. Фильм с id = (тут подставить значение айдишника фильм) не найден.
И не забывай отвечать на комментарии=)

2024-01-13 01:08 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>          List<User> users = userService.getUsers();
Лог не перенес

2024-01-13 01:08 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<User> getFriendsUser(@PathVariable long id) {
Не исправил

2024-01-13 01:08 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        Set<Long> friendsId = new HashSet<>(user.getFriends());
Не исправил

2024-01-13 09:46 UTC, AleksandrRudinskiy commented
Дмитрий привет, я большинство замечаний и особенно (сторейдж - сервис - контроллер) исправил еще в прошлый раз, почему тебе попала не конечная версия - не знаю(. В итоге самый последний commit "Sprint_10#19" там я учел все твои замечания.

2024-01-14 21:09 UTC, dgumich requested changes

2024-01-14 21:09 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return user.getFriends().stream()
Происходит смешивание межслойное смешивание логики. Не должно быть так. 
Как должно быть: в контроллере вызываем только один метод. 
userService.getUsersFriends(userId)
Все, один метод.
Уже в сервисе мы достаем из стореджа пользователя и делаем эту логику.
Сначала сделал логику в контроллерах, но написал же, она должна быть в сервисах.
Сейчас вынес ее в сторедж. Но сторедж - это не сервисный слой, здесь да, может быть логика, но только связанная с хранением, а не доставанием из объекта списка. В следующий раз, думаю, всё-таки вынесешь в сервисы=)
Легко ответить: логика работает с мапой? Нет, тогда здесь ей не место, надо вынести в сервисный слой.

2024-01-14 21:09 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        user.getFriends().add(friendId);
Аналогично, мы работаем с мапой? Нет. Тогда почему данный метод/логика находится не в сервисном слое, а стородже?

2024-01-14 21:09 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        Set<Long> updateFriends = new HashSet<>(user.getFriends());
Аналогично, работаем с мапой? Нет. Тогда логика должна быть в сервисном слое

2024-01-14 21:09 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        updateFriends.remove(friendId);
Опять промежуточный сет, который не нужен

2024-01-14 21:09 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return user1.getFriends()
Если не работаем с мапой, данная логика должна быть в сервисном слое

2024-01-14 21:09 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        film.getLikes().remove(userId);
Никак не работаем с мапой, данная логика должна быть в сервисном слое.

2024-01-14 21:09 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        film.getLikes().add(userId);
Аналогично, не работаем с мапой, логика должна быть в сервисном слое

2024-01-14 21:09 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>          List<User> users = userService.getUsers();
Когда-нибудь перенесёшь данный лог?=)

2024-01-15 00:14 UTC, AleksandrRudinskiy commented
Дмитрий спасибо тебе за сделанные комментарии - они помогли мне очень понять слои!

2024-01-15 20:49 UTC, dgumich requested changes

2024-01-15 20:49 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (!films.containsKey(id)) {
Почему эта логика в сторедже? Это бизнес логика, о чем говорил уже не раз=)
Вся эта логика должна быть в сервисном слое.
Вся. 
Сторедж - только взять/положить/обновить данные из мапы. 
Надо сделать по аналогии с  getCommonFriends

2024-01-15 20:49 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        film.getLikes().add(userId);
Логика должна быть в сервисном слое, а не в сторедже.
Надо сделать по аналогии с getCommonFriends

2024-01-15 20:49 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        user.getFriends().add(friendId);
Логика должна быть в сервисном слое.
Надо сделать по аналогии с getCommonFriends

2024-01-15 20:49 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(f -> secondUser.getFriends().contains(f))
Тут лучше вынести сет в отдельную переменную, код будет лучше читаться, но да, сделал правильно.
Теперь по аналогии с этим методом надо вынести логику и стореджей в сервисные классы.

2024-01-15 20:49 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        User user = getUserById(id);
Логика должна быть в сервисном классе.
Надо сделать по аналогии с getCommonFriends

2024-01-15 20:49 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    UserStorage userStorage;
Поле должно быть приватным и финальным

2024-01-16 05:36 UTC, AleksandrRudinskiy commented
Дмитрий, замечания учел

2024-01-16 11:09 UTC, AleksandrRudinskiy commented
Избавился от методов getMap в сервисах, сделал методы add  void, перенес валидацию из сторейджа)

2024-01-17 02:10 UTC, dgumich approved these changes

2024-01-17 02:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.status(HttpStatus.OK)
Надо добавить логирование

2024-01-17 02:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.status(HttpStatus.OK)
И здесь тоже должно быть логирование

2024-01-17 02:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.status(HttpStatus.OK)
И здесь должно быть логирование

2024-01-17 02:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> -        validateUser(user);
Надо добавить логирование

2024-01-17 02:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.OK)
И здесь тоже надо добавить логирование

2024-01-17 02:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.OK)
И здесь логирование нужно

2024-01-17 02:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.OK)
И здесь логирование

2024-01-17 02:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                .sorted((a, b) -> b.getLikes().size() - a.getLikes().size())
Данная логика ок в сторедже, потому что по сути это запрос к БД. Ты просто просишь отдать n фильмов, отсортированные по лайкам. Так что это ок оставить данную логику в сторедже

2024-01-23 15:18 UTC, closed without merging