Add database
AleksandrRudinskiy/java-filmorate pull request #4
Opened 2024-02-11 12:38 UTC by AleksandrRudinskiy

2024-02-11 19:21 UTC, AleksandrRudinskiy commented
Высылаю на ревью)

2024-02-12 21:57 UTC, dgumich requested changes

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.status(HttpStatus.OK)
Надо добавить логирование

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.status(HttpStatus.OK)
Здесь тоже надо добавить логирование

2024-02-12 21:57 UTC, dgumich commented on src/main/resources/schema.sql
> +  film_name varchar,
Надо указывать размер, varchar(100)/varchar(200) и тд

2024-02-12 21:57 UTC, dgumich commented on src/main/resources/schema.sql
> +  releaseDate timestamp,
release_date. В бд названия дают через нижнее подчеркивание, а не камел кейсом.
Кроме того советую более внимательно выбирать тип данных. timestamp учитывает время. Вот подумай, ты знаешь точно время выхода фильма? Думаю, что нет, тебе нужна только дата, а на часы/минуты/секунды тебе без разницы. В таком случае больше подойдет тип данный Date https://h2database.github.io/html/grammar.html#date

2024-02-12 21:57 UTC, dgumich commented on README.md
> +![ER](Schema_DB_filmorate.png)
По таблице: надо исправить user_friends. friend_id это же не просто айди, а айди какого-нибудь юзера. Надо сделать внешним ключом по аналогии с user_id

2024-02-12 21:57 UTC, dgumich commented on src/main/resources/data.sql
> +INSERT INTO category SELECT 1, 'G' WHERE NOT EXISTS (SELECT category_id FROM category WHERE category_id = 1);
Зачем такая сложная конструкция?=)

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        log.debug("Current number of genres: {}", genres.size());
Разный уровень логирования. Debug очень низкий уровень, чаще всего используют для отладочных сообщений. Здесь больше подойдет info

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +    List<Genre> getGenres();
Лучше будет getAllGenres, а то непонятно, какие именно жанры достаешь

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDaoImpl.java
> +
Если внедряешь зависимость через конструктор все равно лучше писать аннотацию @Autowired над конструктором. Для наглядности и читаемости кода.

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +@AllArgsConstructor
Надо делать все в одном стиле. Если создаешь конструкторы через ломбок, то создавай везде через него.

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String sql = "select * from films";
Вот тут проблема. Ты добавил новые поля в фильм (жанр и все такое). Но таблица с фильмами не содержит эти данные, это другие таблицы. Получается, нам нужно сделать join таблиц. Твой подход не правильный (вытягивать из бд фильмы и потом по айди жанры и тд) потому что создает множество запросов вместо одного.

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            film.setMpa(findMpaByCategoryId(categoryId));
Это вообще что?=) У нас уже должно быть Mpa, мы достаем Mpa из базы по айди (по идее точно такое же достанем) и его сетапим в фильм? Зачем? Какой профит?

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        film.setLikes(new HashSet<>(findLikesByFilmId(id)));
Это зачем делаешь? Понимаешь, что с добавлением в бд это никак не связано? Мы уже добавили фильм в бд. Сейчас мы просто добавляем к объекту лайки. Зачем? Откуда у фильма лайки, если мы его только добавили?

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        film.setGenres(new ArrayList<>(findGenresByFilmId(id)));
А это зачем? У фильма или есть жанры, которые были в самом начале или нет. Откуда они могут взяться в бд, если мы только добавляем фильм?

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        jdbcTemplate.update("UPDATE films SET category_id = ? WHERE film_id = ?", categoryId, id);
И это нам зачем?=)

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public Collection<Long> findLikesByFilmId(long filmId) {
Во первых метод должен быть приватным, так как это внутренняя логика. Во вторых эти данные должны подтягиваться с помощью джойна таблиц, а не отдельного запроса

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Film> addLike(@PathVariable long filmId, @PathVariable long userId) {
Зачем мы в принципе в случае лайка фильма возвращаем фильм? Мы же просто должны добавить лайк фильму и все

2024-02-12 21:57 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes;
Зачем нам это поле? В ТЗ ничего про него не нашел. Точно нужно?

2024-02-14 11:06 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.status(HttpStatus.OK)
Логирование добавил

2024-02-14 11:07 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.status(HttpStatus.OK)
Логирование добавил

2024-02-14 11:12 UTC, AleksandrRudinskiy commented on src/main/resources/schema.sql
> +  film_name varchar,
Размер varchar везде указал

2024-02-14 11:33 UTC, AleksandrRudinskiy commented on src/main/resources/schema.sql
> +  releaseDate timestamp,
Исправил на нижнее подчеркивание release_date и заменил тип на date

2024-02-14 12:09 UTC, AleksandrRudinskiy commented on README.md
> +![ER](Schema_DB_filmorate.png)
В таблице user_friends поле friend_id сделал внешним ключом

2024-02-14 12:32 UTC, AleksandrRudinskiy commented on src/main/resources/data.sql
> +INSERT INTO category SELECT 1, 'G' WHERE NOT EXISTS (SELECT category_id FROM category WHERE category_id = 1);
Исправил через INSERT / VALUES

2024-02-14 12:33 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        log.debug("Current number of genres: {}", genres.size());
Исправил на log.info(...)

2024-02-14 13:49 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +    List<Genre> getGenres();
Исправил название метода на getAllGenres()

2024-02-14 13:54 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDaoImpl.java
> +
Принято, спасибо. Поменял везде на внедрение через lombok.

2024-02-14 13:55 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +@AllArgsConstructor
Везде сделал внедрение через lombok.

2024-02-15 10:54 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            film.setMpa(findMpaByCategoryId(categoryId));
Убрал это из add

2024-02-15 10:59 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        film.setLikes(new HashSet<>(findLikesByFilmId(id)));
film.setLikes(new HashSet<>(findLikesByFilmId(id))) убрал из метода add

2024-02-15 11:03 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        film.setGenres(new ArrayList<>(findGenresByFilmId(id)));
Точно, убрал из add.

2024-02-15 11:06 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        jdbcTemplate.update("UPDATE films SET category_id = ? WHERE film_id = ?", categoryId, id);
Согласен, убрал это.

2024-02-15 11:14 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Film> addLike(@PathVariable long filmId, @PathVariable long userId) {
Исправил на void.

2024-02-15 15:00 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public Collection<Long> findLikesByFilmId(long filmId) {
Удалил этот метод, теперь обхожусь без него.

2024-02-15 15:02 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes;
Не уверен, но раз фильм должен по ТЗ вроде как иметь жанры, рейтинг и лайки до решил реализовать связь таким образом, добавив эти поля в класс Film. Все три эти поля не нужны?

2024-02-15 15:06 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String sql = "select * from films";
Я сделал JOIN в запросе, чтобы получать жанры, но при этом не смог дойти как сделать тогда маппинг Film при имеющихся тех 3х полях о которых ты мне написал ниже.

2024-02-15 15:12 UTC, AleksandrRudinskiy commented
Дмитрий, я внес исправления, но кажется основное твое замечание по поводу getAllFilms() через единый запрос так и не смог реализовать. По поводу "лишних" трех полей в Film - правильно ли я понял что так тоже не правильно и ты ждешь наверное от меня вспомогательный класс, который будет реализовывать связь Film с лайками жанрами и рейтингом. Не совсем понял... Надеюсь что теперь логика стала более понятной для ревью и попытка "сгорит" не зря (

2024-02-16 15:18 UTC, dgumich commented
> Дмитрий, я внес исправления, но кажется основное твое замечание по поводу getAllFilms() через единый запрос так и не смог реализовать. По поводу "лишних" трех полей в Film - правильно ли я понял что так тоже не правильно и ты ждешь наверное от меня вспомогательный класс, который будет реализовывать связь Film с лайками жанрами и рейтингом. Не совсем понял... Надеюсь что теперь логика стала более понятной для ревью и попытка "сгорит" не зря (

Ничего не бывает зря=) Не три поля, только последнее. Не уверен, что есть в ТЗ. Тут дело не в том, что не правильно, а то, что ты добавил доп информацию к фильму, которая не нужна. В этом ничего плохого нет, просто если это усложняет работу, то можно не делать=) Поэтому и спрашиваю, точно ли нужно? Думаю, лучше уточнить у наставника, потому что в ТЗ явно не написано. Если скажет, что делать не надо, то если хочешь, можешь убрать, что бы упросить задачу=)

2024-02-16 15:18 UTC, dgumich requested changes

2024-02-16 15:18 UTC, dgumich commented on Schema_DB_filmorate.png
Зачем эта схема, если уже есть ER-schema-java-filmorate.png ?

2024-02-16 15:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ResponseEntity<>(
Надо логировать, когда отлавливаешь исключения и отсылаешь ответ с ошибкой. Добавь логирование во все три метода

2024-02-16 15:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>          log.debug("Current number of users: {}", users.size());
Разный уровень логирования. Вообще debug очень низкий уровень и часто отключен. Используется только для отладки приложения, когда добавляются разные технические логи. В данном случае надо так же использовать уровень info

2024-02-16 15:18 UTC, dgumich commented on src/main/resources/Schema_DB_filmorate_1.png
И это зачем? У тебя три схемы, две из которых старые, без фикса=)

2024-02-16 15:18 UTC, dgumich commented on src/main/resources/schema.sql
> +  friendship char(20)
Поле создано, но нигде не используешь. Кроме того точно нужен char? Может подойдет больше boolean?

2024-02-16 15:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        String sql = "select * from films";
А где join?=) Запрос остался такой же "select * from films"

2024-02-16 15:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
Вот это надо уже переписать на запрос. Теперь мы можем создать запрос, который достанет всех друзей по айди друга. Иначе получается множество запросов.

2024-02-16 15:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUserById(id) == null) {
Тут мы делаем два запроса, хотя достаточно одного. Достали пользователя, есть? Тогда возвращаем, нет? Тогда бросаем исключение. Теперь мы ходим в бд, так что не получится как с мапой постоянной вызывать get =)

2024-02-16 15:18 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        getUserById(friendId);
Мы достали друга и ничего не делаем. Ок, допустим это проверка, что человек существует. Но тогда такую же надо сделать для id, а то будем добавлять в друзья не существующему человек. Кроме того у тебя есть отдельный метод для такой проверки.

2024-02-17 05:20 UTC, AleksandrRudinskiy commented on Schema_DB_filmorate.png
Лишнюю схему удалил.

2024-02-17 05:33 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ResponseEntity<>(
Добавил логирование на уровне warn.

2024-02-17 05:39 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>          log.debug("Current number of users: {}", users.size());
Спасибо за пояснение, исправил на info.

2024-02-18 02:30 UTC, AleksandrRudinskiy commented on src/main/resources/Schema_DB_filmorate_1.png
Удалил файл из ветки main.

2024-02-18 03:01 UTC, AleksandrRudinskiy commented on src/main/resources/schema.sql
> +  friendship char(20)
Поменял тип поля в схеме и в коде на boolean.

2024-02-18 04:24 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ResponseEntity<>(
Поменял на уровень info)

2024-02-19 08:21 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
Переписал на единый запрос через join, понадобилось создать новый класс FilmsDbGenres, поля которого соответствуют двум ячейкам из строки запроса: film_id и genre_id. Получилось в коде грамоздко конечно и с промежуточными коллекциями, но наставник сказал, что главное что бы код работал).

2024-02-19 08:26 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
В классах UserService и UserDbStorage (метод getUsersFriends) переписал на единый запрос.

2024-02-19 08:29 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUserById(id) == null) {
Что бы 2 раза не ходить в БД ввел User user =... и его уже проверяю.

2024-02-19 08:43 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        getUserById(friendId);
Оформил проверки друга и юзера через метод userStorage.isAlreadyExists(...).

2024-02-19 09:49 UTC, AleksandrRudinskiy commented
Дмитрий, исправления внес. По полю лайков у фильма наставник сказал опционально. Я оставил. Переписал запросы на все фильмы и пользователей через join. Надеюсь стало не хуже.

2024-02-20 01:51 UTC, dgumich requested changes

2024-02-20 01:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ResponseEntity<>(
Чаще всего используют info/error. Инфо для обычных сообщений, а ерор когда прям супер пупер важная и серьезная ошибка.

2024-02-20 01:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Data
А @Data зачем контроллеру?=) Не надо обвешивать класс аннотациями бездумно. Надо понимать, что ты добавляешь.

2024-02-20 01:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@Data
Аналогично, зачем нам для контроллера @Data?

2024-02-20 01:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Data
Зачем????=)

2024-02-20 01:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Getter
Гетер зачем? Что собираешься получать из сервиса? Тут только два поля=)

2024-02-20 01:51 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
Тут тоже множество запросов к бд, хотя можно обойтись одним. Надо переписать логику сервиса/стореджа.

2024-02-20 05:09 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Data
Убрал аннотацию @Data.

2024-02-20 05:10 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Data
В ErrorHandler во всех 3-х поменял уровень логирования на error.

2024-02-20 05:11 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@Data
Убрал аннотацию @Data из MpaController.

2024-02-20 05:13 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@Data
Убрал @Data, добавил @AllArgsConstructor для внедрения зависимости UserService userService.

2024-02-20 05:15 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Getter
Согласен, убрал @Getter.

2024-02-20 07:22 UTC, AleksandrRudinskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::getUserById)
Метод getCommonFriends() в UserService исправил, добавил запрос в БД в аналогичный метод класса UserDbStorage так, что бы список общих друзе получался за один запрос к БД через JOIN.

2024-02-20 07:35 UTC, AleksandrRudinskiy commented
Дмитрий, замечания учел: убрал неиспользуемые аннотации из классов, исправил уровень логирования в ExceptionHandler, переписал запрос на получение общих друзей в сервисе и сторейдже на получение из БД.
Надеюсь продвинулся вперед.

2024-02-20 21:21 UTC, dgumich requested changes

2024-02-20 21:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            return userStorage.add(user);
Не, метод update на то и метод апдейт, что обновляет пользователя, а не создает в случае необходимости.
Надо мухи отдельно, котлеты отдельно. Создавать пользователей через create, обновлять через update. Так что эту часть надо удалить. Есть пользователь - обновили его. Нет - ничего не сделали/бросили исключение, что пользователя нет.

2024-02-20 21:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.isAlreadyExists(user.getId())) {
userStorage.isAlreadyExists вынеси в локальную переменную, а то опять два раза ходим к базе только для того, что бы проверить существует ли пользователь или нет (строки 31 и 33)

2024-02-20 21:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new RuntimeException();
Если кидаешь исключения, то надо передавать понятное сообщение, где и почему это исключение было выброшено.

2024-02-20 21:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (getFilmById(film.getId()) == null) {
В этом методе намудрил с логикой. Мало того, что для обновления фильма мы ходим 4 раза в бд. Так еще и логика друг другу противоречит: достаем фильм по айди и проверяем на null. Если его нет - бросаем исключение. Соответственно проверка на строке 52 уже не нужна (раз мы туда дошли, то фильм достали и проверили, что он есть). Но мы опять идем бд и проверяем то, что уже проверили на строке 49. Но каким-то образом мы можем еще попасть в условия на строке 54. Хотя это невозможно: если фильма нет, то мы уже исключение кинули, если он есть, то обновили. Так что строка 54 просто логически недостижима. Но мы не успокоились и на всякий случай добили блок else, в котором создаем фильм. В общем велосипед=) Метод обновления должен обновлять, а не создавать. Есть фильм - обновили, нет фильма - бросили исключение/ничего не сделали. Надо пофиксить.

2024-02-20 21:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmsDbGenres.java
> +public class FilmsDbGenres {
dao - это от data access object. Так же их по другому называют repository. То есть те объекты, которые работают с бд. То что хранится в бд, то это entity или model. В данном случае у нас класс никак не дао, а модель, поэтому должен быть в правильном пакете.

2024-02-20 21:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbFriends.java
> +public class UserDbFriends {
Аналогично, класс не является дао, и должен быть в пакете моделей.

2024-02-20 21:21 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Getter
Зачем нам гетер в контроллере?

2024-03-05 08:25 UTC, merged